---
title: "Create Statistical Reports"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Create Statistical Reports}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# reporter 

The **reporter** package creates regulatory-style, statistical reports. It was designed
to produce Tables, Listings, and Figures (TLFs) for the 
the pharmaceutical, biotechnology, and medical-device industries.
However, the functions are generalized enough to provide statistical reporting
for any industry.  The package is written in Base R, and has no dependencies on
any other reporting package.

The package is intended to give R programmers flexible 
report layout capabilities 
and a choice of output formats. The package will 
initially focus on printable, file-based 
output formats, as there are already numerous R packages that 
provide tabular reporting in HTML. 
The current version supports TXT, RTF, and PDF output types.   

The **reporter** package is distributed under a [Creative Commons non-commercial 
license](https://creativecommons.org/licenses/by-nc/4.0).  It is available 
for personal and organizational use, but cannot be used to create a commercial 
product without permission of the license holder.

## Key Features

The **reporter** package contains the following key features:

* Titles, footnotes, page header, and page footer are repeated on each page
* Supports header labels and spanning headers 
* Calculates default columns widths automatically
* Includes automatic wrapping and splitting of wide and long tables
* Integrates with the **fmtr** package to format numeric, date, and character data
* Plots from the popular **ggplot2** package can be added to RTF and PDF reports
* Allows appending multiple tables to a report, multiple tables to a page, 
and intermingling of text, tables, and plots
* Supports in-report date/time stamps and "Page X of Y" page numbering


## How to use **reporter**
There are four steps to creating a report:

* Create report 
* Create report content
* Add content to the report
* Write out the report 

You can create the report with the `create_report()` function.  Content is
created with the `create_table()`, `create_text()`, or `create_plot()`
functions.  Add content to the report with the `add_content()` function. 
Finally, the report can be written to a file with the `write_report()` function.  

In addition to these primary functions, there are several secondary functions
to help you formalize the report.  All available functions are shown in
the subsequent glossary.


## Glossary of Functions

Below are the functions available in the **reporter** package, and a brief
description of their use.  For additional information, see the help text:

### Report Functions

* `create_report()`: Define a report object  
* `options_fixed()`: Set options for fixed width (text) reports  
* `set_margins()`: Set margins for the report  
* `page_header()`: Define a page header  
* `page_footer()`: Define a page footer  
* `add_content()`: Add content to the report  
* `write_report()`: Write the report to a file  

### Table functions

* `create_table()`: Define a table object  
* `spanning_header()`: Define a spanning header  
* `stub()`: Define a stub column  
* `columns_defaults()`: Set default column attributes
* `define()`: Specify settings for a column  

### Text and Plot functions

* `create_text()`: Define a text object  
* `create_plot()`: Define a plot object 

### Title/Footnote Functions 
* `titles()`: Set titles for the object  
* `footnotes()`: Set footnotes for the object 
* `title_header()`: A combined title/header block 
* `page_by()`: Creates separate pages by a variable

